/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BurnMilkToken__factory } from "./BurnMilkToken__factory";
export { MilkToken__factory } from "./MilkToken__factory";
